In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

from scipy.stats import pearsonr
import seaborn as sns
import statsmodels.api as sm

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from tabulate import tabulate


import warnings
warnings.filterwarnings('ignore')

### Question 3

In [16]:
Diabetes = pd.read_excel("Diabetes_Data.xlsx")
x_diabetes = Diabetes[["AGE","SEX","BMI","BP","S1","S2","S3","S4","S5","S6"]]#independent
y_diabetes = Diabetes[["Y"]]#dependent  

#correlation 
corr_ = x_diabetes.corr()
#print(corr_)

#heatmap plotting
mask = np.zeros_like(corr_, dtype=bool)
mask[np.triu_indices_from(mask)] = True
corr_[mask] = np.nan

(corr_
 .style
 .background_gradient(cmap='coolwarm', axis=None, vmin=-1, vmax=1)
 .highlight_null(null_color='#f1f1f1')  # Color all Nan values grey
 .set_precision(2))

In [17]:
#multivariate and adding a constant to dataframe..used 1 coz it doesnt change a value.
Diabetes_Df = pd.concat([pd.Series(1, index=Diabetes.index, name='Constant'), Diabetes], axis=1)

#drop the response var column
X = Diabetes_Df.drop(Diabetes_Df.columns[[11]],axis = 1)
Y = Diabetes_Df[["Y"]]

#model creation
model = sm.OLS(Y,X)
model1 = model.fit()

#rsquared adjusted
y_pred = model1.predict(X)

#mean square
msqre_value = mean_squared_error(Y,y_pred)


print(model1.pvalues)
print("Mean squared error is:",msqre_value)
print("Adjusted R squared value is:",model1.rsquared_adj)

Constant    1.016617e-06
AGE         8.670306e-01
SEX         1.041671e-04
BMI         4.296391e-14
BP          1.024278e-06
S1          5.794761e-02
S2          1.603902e-01
S3          6.347233e-01
S4          2.734587e-01
S5          1.555899e-05
S6          3.059895e-01
dtype: float64
Mean squared error is: 2859.69634758675
Adjusted R squared value is: 0.5065592904853231

In [7]:
#forward regression

def forward_regression(X, y,
                       threshold_in,
                       verbose=False):
    initial_list = []
    included = list(initial_list)
    while True:
        changed=False
        excluded = list(set(X.columns)-set(included))
        new_pval = pd.Series(index=excluded)
        for new_column in excluded:
            model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included+[new_column]]))).fit()
            print(model.pvalues)
            new_pval[new_column] = model.pvalues[new_column]
        best_pval = new_pval.min()
        if best_pval < threshold_in:
            best_feature = new_pval.idxmin()
            included.append(best_feature)
            changed=True
            if verbose:
                print('Add  {:30} with p-value {:.6}'.format(best_feature, best_pval))
                
        if not changed:
            break

    return included

forward_regression(x_diabetes,y_diabetes,0.05,verbose=True)

const    0.001760
S1       0.000007
dtype: float64
const    4.401020e-04
BP       1.649372e-22
dtype: float64
const    2.710866e-03
S6       7.580083e-17
dtype: float64
const    7.433496e-31
SEX      3.664293e-01
dtype: float64
const    4.437242e-12
AGE      7.055686e-05
dtype: float64
const    1.892632e-05
S4       2.304253e-21
dtype: float64
const    7.126475e-17
S5       8.826459e-39
dtype: float64
const    5.188287e-64
S3       6.162865e-18
dtype: float64
const    4.301065e-12
S2       2.359848e-04
dtype: float64
const    1.751618e-10
BMI      3.466006e-42
dtype: float64
Add  BMI                            with p-value 3.46601e-42
const    3.792195e-10
BMI      2.319276e-38
S1       7.961267e-02
dtype: float64
const    2.020878e-18
BMI      3.047885e-29
BP       1.725601e-09
dtype: float64
const    3.239627e-14
BMI      3.871059e-31
S6       1.165706e-05
dtype: float64
const    4.674330e-09
BMI      6.288631e-42
SEX      8.225591e-01
dtype: float64
const    2.455363e-11
BMI      1.309246e-39
AGE      3.638563e-02
dtype: float64
const    8.033051e-13
BMI      7.017075e-29
S4       5.888280e-08
dtype: float64
const    5.249758e-29
BMI      1.168996e-23
S5       3.039635e-20
dtype: float64
const    4.115392e-01
BMI      1.810748e-31
S3       4.055195e-07
dtype: float64
const    7.259699e-10
BMI      3.229807e-39
S2       5.757554e-01
dtype: float64
Add  S5                             with p-value 3.03963e-20
const    6.316956e-28
BMI      2.867675e-24
S5       2.026974e-21
S1       3.333891e-03
dtype: float64
const    1.158977e-32
BMI      5.551045e-19
S5       5.557158e-16
BP       3.742620e-05
dtype: float64
const    1.488582e-27
BMI      1.838220e-21
S5       1.903978e-16
S6       1.467762e-01
dtype: float64
const    2.010608e-27
BMI      8.002827e-24
S5       1.170986e-20
SEX      1.444255e-01
dtype: float64
const    1.115576e-28
BMI      1.946870e-23
S5       2.974533e-19
AGE      8.157956e-01
dtype: float64
const    7.972106e-25
BMI      2.884551e-22
S5       6.645447e-14
S4       3.914650e-01
dtype: float64
const    4.498733e-11
BMI      1.623888e-20
S5       2.053029e-16
S3       3.770117e-03
dtype: float64
const    1.922565e-28
BMI      3.127332e-24
S5       9.208421e-21
S2       9.037458e-02
dtype: float64
Add  BP                             with p-value 3.74262e-05
const    6.715025e-32
BMI      1.873430e-19
S5       5.030845e-18
BP       1.700049e-05
S1       1.454431e-03
dtype: float64
const    1.190385e-30
BMI      4.079354e-18
S5       3.762158e-14
BP       9.389986e-05
S6       5.284324e-01
dtype: float64
const    9.902446e-32
BMI      7.038410e-19
S5       1.380917e-16
BP       6.007440e-06
SEX      1.743245e-02
dtype: float64
const    1.823435e-28
BMI      1.119057e-17
S5       9.518419e-11
BP       3.262679e-05
S4       3.096380e-01
dtype: float64
const    1.915072e-32
BMI      5.540399e-19
S5       4.627944e-16
BP       2.754857e-05
AGE      4.112309e-01
dtype: float64
const    1.175155e-13
BMI      4.873755e-16
S5       1.640773e-12
BP       1.909239e-05
S3       1.851607e-03
dtype: float64
const    3.179296e-32
BMI      1.262581e-19
S5       1.028220e-16
BP       2.763333e-05
S2       6.225047e-02
dtype: float64
Add  S1                             with p-value 0.00145443
const    1.647864e-30
BMI      2.147538e-18
S5       1.824265e-16
BP       5.806463e-05
S1       1.091835e-03
S6       3.299199e-01
dtype: float64
const    7.119361e-31
BMI      2.234253e-19
S5       6.931194e-19
BP       1.988410e-06
S1       7.959889e-04
SEX      9.230560e-03
dtype: float64
const    2.494710e-25
BMI      2.340084e-17
S5       4.189496e-13
BP       9.511717e-06
S1       1.753044e-04
S4       2.539962e-02
dtype: float64
const    9.115538e-32
BMI      2.006583e-19
S5       5.240804e-18
BP       2.025146e-05
S1       1.953247e-03
AGE      6.943615e-01
dtype: float64
const    1.327705e-14
BMI      9.467696e-17
S5       5.897037e-13
BP       1.252640e-05
S1       2.303291e-02
S3       2.976717e-02
dtype: float64
const    8.603175e-32
BMI      2.629916e-16
S5       1.004489e-18
BP       1.254786e-05
S1       3.860581e-04
S2       1.467846e-02
dtype: float64
Add  SEX                            with p-value 0.00923056
const    3.778883e-30
BMI      4.271883e-18
S5       3.835141e-17
BP       8.143499e-06
S1       4.980919e-04
SEX      5.930660e-03
S6       1.851017e-01
dtype: float64
const    2.096840e-21
BMI      3.110875e-16
S5       1.166289e-12
BP       1.811919e-07
S1       9.556135e-06
SEX      2.102307e-04
S4       5.434864e-04
dtype: float64
const    8.683421e-31
BMI      2.438120e-19
S5       8.285996e-19
BP       3.142438e-06
S1       9.750504e-04
SEX      1.005930e-02
AGE      8.983645e-01
dtype: float64
const    4.582918e-10
BMI      2.431181e-15
S5       2.128982e-12
BP       2.760103e-07
S1       4.361403e-02
SEX      2.023114e-04
S3       6.054228e-04
dtype: float64
const    2.750430e-30
BMI      6.687185e-15
S5       1.938635e-21
BP       2.786882e-07
S1       3.122573e-06
SEX      1.758474e-04
S2       2.723024e-04
dtype: float64
Add  S2                             with p-value 0.000272302
const    3.065167e-29
BMI      4.083348e-14
S5       1.202844e-19
BP       1.149518e-06
S1       3.415822e-06
SEX      1.240442e-04
S2       3.705089e-04
S6       2.721107e-01
dtype: float64
const    3.110632e-21
BMI      7.248161e-15
S5       6.398602e-09
BP       1.817887e-07
S1       2.810070e-03
SEX      1.066132e-04
S2       1.104828e-01
S4       2.619190e-01
dtype: float64
const    3.295026e-30
BMI      7.170514e-15
S5       2.309666e-21
BP       5.082306e-07
S1       3.480635e-06
SEX      1.980671e-04
S2       2.786322e-04
AGE      9.514711e-01
dtype: float64
const    1.857504e-06
BMI      7.932792e-15
S5       1.319999e-05
BP       2.702627e-07
S1       1.087649e-01
SEX      1.679425e-04
S2       2.025559e-01
S3       7.136963e-01
dtype: float64

['BMI', 'S5', 'BP', 'S1', 'SEX', 'S2']

In [18]:
#mse for stepwise model
X2 = Diabetes_Df.drop(columns=["AGE","S3","S4","S6","Y"],axis = 1)
Y2 = Diabetes_Df[["Y"]]
 
model2 = sm.OLS(Y2,X2)
model2 = model2.fit()
y2_pred = model2.predict(X2)
#r_square = model2.rsquared


mse2_value = mean_squared_error(Y2,y2_pred)
#model2 mse and r square values
print("MSE value for useful forward regression variables:", mse2_value)
print("R_square value is:",model2.rsquared)

MSE value for useful forward regression variables: 2876.683251787016
R_square value is: 0.5148837959256445

In [9]:
print("forward selection useful features are:")
print(model2.pvalues)

forward selection useful features are:
Constant    2.750430e-30
SEX         1.758474e-04
BMI         6.687185e-15
BP          2.786882e-07
S1          3.122573e-06
S2          2.723024e-04
S5          1.938635e-21
dtype: float64

### Question 4

In [20]:
#data set
Titanic = pd.read_csv("titanic3.csv")

#4.2 probability of survival for a passenger on the titanic.
survivors = Titanic[Titanic["survived"] ==1].shape[0]
total_passengers = Titanic["sex"].count()

p_surviving = survivors/total_passengers
print("The probability of a passenger surviving is {:0.3f}".format(p_surviving))

The probability of a passenger surviving is 0.382

In [12]:
#4.3 Provide a table giving survival probabilities broken down by passenger class, gender, and age.
#set limits for age
bins= [0,5,10,15,23,100]
labels = ['Infant','Toddler','Kid','Teen','Adult']
Titanic['AgeGroup'] = pd.cut(Titanic['age'], bins=bins, labels=labels, right=False)

#calculating survival proberbilities
survived_sex = pd.pivot_table(Titanic,index = "survived",columns = "sex", values = "ticket",aggfunc="count")
survived_class = pd.pivot_table(Titanic,index = "survived",columns = "pclass", values = "ticket",aggfunc="count")
survived_age = pd.pivot_table(Titanic,index = "survived",columns = "AgeGroup", values = "ticket",aggfunc="count")

print("Number of survival by gender")
print(survived_sex)
print("Number of survival by class")
print(survived_class)
print("Number of survival by age")
print(survived_age)
print("\n")

#probability survival by Age 
PageInf = survived_age["Infant"][1]/survived_age["Infant"].sum()
PageTodd = survived_age["Toddler"][1]/survived_age["Toddler"].sum()
PageKid = survived_age["Kid"][1]/survived_age["Kid"].sum()
PageTeen = survived_age["Teen"][1]/survived_age["Teen"].sum()
PageAd = survived_age["Adult"][1]/survived_age["Adult"].sum()

#probability survival by class
Pclass1 = survived_class[1][1]/ survived_class[1].sum()
Pclass2 = survived_class[2][1]/ survived_class[2].sum()
Pclass3 = survived_class[3][1]/ survived_class[3].sum()

#probability survival by gender
Pfemale = survived_sex["female"][1]/survived_sex["female"].sum()
Pmale = survived_sex["male"][1]/survived_sex["male"].sum()


#tabulate   
head = ["Female", "Male","Clas1 "," Clas2","Clas3","Infant","Toddler","Kid","Teen","Adult"]
stats = [(Pfemale,Pmale,Pclass1,Pclass2,Pclass3,PageInf,PageTodd,PageKid,PageTeen,PageAd)]
print(tabulate(stats, headers=head, tablefmt="grid")) 
print()

Number of survival by gender
sex       female  male
survived
0            127   682
1            339   161
Number of survival by class
pclass      1    2    3
survived
0         123  158  528
1         200  119  181
Number of survival by age
AgeGroup  Infant  Toddler  Kid  Teen  Adult
survived
0             18       14   16   141    430
1             33       17   11    84    282


+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+
|   Female |     Male |   Clas1  |    Clas2 |    Clas3 |   Infant |   Toddler |      Kid |     Teen |    Adult |
+==========+==========+==========+==========+==========+==========+===========+==========+==========+==========+
| 0.727468 | 0.190985 | 0.619195 | 0.429603 | 0.255289 | 0.647059 |  0.548387 | 0.407407 | 0.373333 | 0.396067 |
+----------+----------+----------+----------+----------+----------+-----------+----------+----------+----------+

In [22]:
# 4.4 Build a logistic regression model for survival rates based on passenger class, sex, and age.
#function to fill age nan values with mean
def add_age(cols):
    age = cols[0]
    pclass = cols[1]
    if pd.isnull(age):
        return int(Titanic[Titanic["pclass"] == pclass]["age"].mean())
    else:
        return age
Titanic["age"] = Titanic[["age", "pclass"]].apply(add_age,axis=1) 

#change sex values from string to numeric
pd.get_dummies(Titanic["sex"])
sex_new = pd.get_dummies(Titanic["sex"],drop_first=True)
Titanic = pd.concat([Titanic,sex_new],axis=1)

#creating variables
x_survived = Titanic[["pclass","male","age"]]#predictor
y_survived = Titanic["survived"]

#regression line
logmodel = LogisticRegression()
logmodel.fit(x_survived,y_survived)

#predictions
y_predictions = logmodel.predict(x_survived)

#pvalues
print(logmodel.coef_)
print("\n")

#confusion matrix
c_matrix = confusion_matrix(y_survived,y_predictions)
print("Confusion Matrix")
c_matrix

[[-1.11370347 -1.23020583 -1.23020583 -0.03347261]]


Confusion Matrix

array([[687, 122],
       [158, 342]], dtype=int64)

In [23]:
#confusion matrix accuracy
tn, fp, fn, tp = c_matrix.ravel()
accuracy = ((tn+tp)/(tn+fp+fn+tp))*100
print("model accuracy is {:.3f}".format(accuracy),"%")

model accuracy is 78.610 %